name: CDQR • Incident-to-Fix
on:
  workflow_dispatch:
    inputs:
      log_path:
        description: "Path to incident log file"
        default: "logs/incident.log"

jobs:
  incident:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Summarize log
        run: |
          python tools/log_summarizer.py --log "${{ inputs.log_path }}" --out incident_issue.md
          cat incident_issue.md

      - name: Create Issue
        env: { GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: |
          TITLE="Copilot: Incident Resolver – $(date +%Y-%m-%d_%H:%M)"
          BODY="$(cat incident_issue.md)"
          curl -s -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d "{\"title\":\"$TITLE\",\"body\":${BODY@Q},\"labels\":[\"cdqr-incident\"]}"
