name: CDQR • Risk-Weighted Test Request
on: [pull_request]
jobs:
  risk:
    runs-on: ubuntu-latest
    permissions: { contents: read, issues: write }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Run risk analyzer
        run: |
          pip install pygments
          python tools/risk.py --base origin/${{ github.base_ref }} --head HEAD --out risk.json --md risk_issue.md
          cat risk_issue.md
      - name: Create Issue
        env: { GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: |
          TITLE="Copilot: Risk-Ağırlıklı Test Üretimi – PR #${{ github.event.pull_request.number }}"
          BODY="$(cat risk_issue.md)"
          curl -s -X POST -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d "{\"title\":\"$TITLE\",\"body\":${BODY@Q},\"labels\":[\"cdqr-tests\"]}"
