name: CDQR • Risk-Weighted Test Request

on:
  pull_request:

jobs:
  risk:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run risk analyzer
        shell: bash
        run: |
          pip install pygments
          echo "== listele tools klasörü ==" 
          ls -l tools/ || true
          echo "== risk.py çalıştır ==" 
          python cdqr_hackathon_repo/tools/risk.py || true
          echo "dummy result" > risk_issue.md
          cat risk_issue.md

      - name: Create Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          TITLE="Copilot: Risk-Ağırlıklı Test Üretimi – PR #${{ github.event.pull_request.number }}"
          BODY="$(cat risk_issue.md)"
          curl -s -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues" \
            -d "$(jq -n --arg t "$TITLE" --arg b "$BODY" '{title:$t, body:$b, labels:["cdqr-tests"]}')"
