name: CDQR • Incident-to-Fix

on:
  workflow_dispatch:
    inputs:
      log_path:
        description: "Path to incident log file"
        default: "logs/incident.log"

jobs:
  incident:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Summarize log
        id: sum
        shell: bash
        run: |
          python tools/log_summarizer.py --log "${{ inputs.log_path }}" --out incident_issue.md
          echo "ISSUE_BODY<<'EOF'" >> $GITHUB_OUTPUT
          cat incident_issue.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          TITLE="Copilot: Incident Resolver – $(date +%Y-%m-%d_%H:%M)"
          BODY='${{ steps.sum.outputs.ISSUE_BODY }}'
          curl -s -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues" \
            -d "$(jq -n --arg t "$TITLE" --arg b "$BODY" '{title:$t, body:$b, labels:["cdqr-incident"]}')"
